# Configuración básica de la aplicación
spring.application.name=springboot-applications
server.port=8080

# Configuración de recursos estáticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# Configuración de manejo de errores
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false

# Configuración de logging
logging.level.org.springframework.web=INFO
logging.level.com.informationconfig.spring.app=DEBUG